# Generated by Django 2.2.1 on 2019-05-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=14)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Assunto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=14)),
                ('Password', models.CharField(max_length=50)),
                ('UserType', models.IntegerField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('WeekDay', models.IntegerField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Alunos', models.ManyToManyField(to='serve.Pessoa')),
                ('Aulas', models.ManyToManyField(to='serve.Aula')),
                ('Cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serve.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contador', models.IntegerField()),
                ('Aulas', models.ManyToManyField(to='serve.Aula')),
                ('Pessoas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serve.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradorTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serve.Pessoa')),
                ('Turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serve.Turma')),
            ],
        ),
    ]
