# Generated by Django 2.2.1 on 2019-05-03 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='UserType',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='pessoaaula',
            name='Aulas',
        ),
        migrations.AddField(
            model_name='pessoaaula',
            name='Aulas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serve.Aula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoaaula',
            name='Contador',
            field=models.IntegerField(default=0),
        ),
    ]
