# Generated by Django 2.2.1 on 2019-05-04 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0002_auto_20190503_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='Curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serve.Curso'),
            preserve_default=False,
        ),
    ]
