# Generated by Django 2.2.1 on 2019-05-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0003_aula_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaaula',
            name='Contador',
            field=models.IntegerField(default=-1),
        ),
    ]
