# Generated by Django 2.2.1 on 2019-05-25 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0004_auto_20190525_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='StartDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
