# Generated by Django 2.2.1 on 2019-06-08 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0004_auto_20190608_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='Assunto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='Data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='colaboradorturma',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='EndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='StartDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='EndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='StartDate',
            field=models.DateField(default=datetime.date(2019, 6, 8), null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='EndTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='StartTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='WeekDay',
            field=models.IntegerField(null=True),
        ),
    ]
