# Generated by Django 2.2.1 on 2019-06-08 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0005_auto_20190608_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='StartDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
