# Generated by Django 2.2.1 on 2019-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0005_auto_20190525_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='EndDate',
            field=models.DateField(null=True),
        ),
    ]
